---
title: "thirdRProject"
author: "Zirui"
date: "2024-10-09"
output: html_document
---

```{r}
library(tidyverse)
```
## 1
## 1.1
## (Q1)
```{r}
library(purrr)
impute_by_mean<-function(x){
  mu<-mean(x,na.rm = TRUE)
  impute_f<-function(z){
    if(is.na(z)){
      return(mu)
    }else{
      return(z)
    }
  }
  return(map_dbl(x,impute_f))
}
data<-c(2,5,NA,7,NA,10)
imputed_data<-impute_by_mean(data)
print(imputed_data)
```
## (Q2)
```{r}
library(purrr)
impute_by_median<-function(x){
  med<-median(x,na.rm = TRUE)
  impute_f<-function(z){
    if(is.na(z)){
      return(med)
    }else{
      return(z)
    }
  }
  return(map_dbl(x,impute_f))
}
v<-c(1,2,NA,4)
impute_by_median(v)
```
## (Q3)
```{r}
x<-seq(0,10,by = 0.1)
y<-5*x+1
df_xy<-data.frame(x=x,y=y)
head(df_xy,5)
```
## (Q4)
```{r}
df_xy %>% mutate(z = map2_dbl(x, y, ~.x + .y)) %>% head(5)
sometimes_missing <- function(index, value){
  if(index %% 5 == 0){
    return(NA)
  }else{
    return(value)
  }
}
sometimes_missing(14, 25)
sometimes_missing(15, 25)
library(dplyr)
library(purrr)
x<-seq(0, 10, by = 0.1)
df_xy_missing <- data.frame(x = x) %>% mutate(y = map2_dbl(row_number(), x, ~sometimes_missing(.x, 5 * .y + 1)))
head(df_xy_missing, 10)
```
## (Q5)
```{r}
library(purrr)
impute_by_median <- function(x){
  med <- median(x, na.rm = TRUE)
  impute_f <- function(z){
    if(is.na(z)){
      return(med)
    }else{
      return(z)
    }
  }
  return(map_dbl(x, impute_f))
}
library(dplyr)
df_xy_imputed <- df_xy_missing %>% mutate(y = impute_by_median(y))
head(df_xy_imputed, 6)
```
## 1.2
```{r}
library(readxl)
folder_path <- "C:/Users/mzr/Documents/GitHub/thirdRProject/"
file_name <- "HockeyLeague.xlsx"
file_path <- paste(folder_path, file_name,sep = "")
wins_data_frame <- read_excel(file_path, sheet = "Wins")
wins_data_frame %>% select(1:5) %>% head(3)
tidy_wins_data <- wins_data_frame %>% pivot_longer(cols = -1, names_to = "season", values_to = "results") %>% separate(results, into = c("wins", "total_games"), sep = " of ", convert = TRUE)
head(tidy_wins_data)
```
## (Q1)
```{r}
wins_tidy <- wins_data_frame %>% rename(Team = ...1) %>% pivot_longer(cols = -Team, names_to = "Year", values_to = "Results") %>% separate(Results, into = c("Wins", "Total"), sep = " of ", convert = TRUE) %>% mutate(Year = as.integer(Year))
wins_tidy %>% dim()
wins_tidy %>% head(5)
```
## (Q2)
```{r}
losses_data_frame <- read_excel(file_path, sheet = "Losses")
losses_tidy <- losses_data_frame %>% rename(Team = ...1) %>% pivot_longer(cols = -Team, names_to = "Year", values_to = "Results") %>% separate(Results, into = c("Losses", "Total"), sep = " of ", convert = TRUE) %>% mutate(Year = as.integer(Year))
losses_tidy %>% head(5)
```
## (Q3)
```{r}
hockey_df <- wins_tidy %>% inner_join(losses_tidy, by = c("Team", "Year", "Total")) %>% mutate(
    Draws = Total - Wins - Losses,
    Wins_rt = Wins / Total,
    Losses_rt = Losses / Total,
    Draws_rt = Draws / Total
  )
hockey_df %>% head(5)
```
## (Q4)
```{r}
summary_df <- hockey_df %>% group_by(Team) %>% summarize(
    W_md = median(Wins_rt),
    W_mn = mean(Wins_rt),
    L_md = median(Losses_rt),
    L_mn = mean(Losses_rt),
    D_md = median(Draws_rt),
    D_mn = mean(Draws_rt)
  ) %>% arrange(desc(W_md))
summary_df %>% head(8)
```
## 1.3
## (Q1)
```{r}
library(dplyr)
library(purrr)
num_red_balls <- 3
num_blue_balls <- 7
total_draws <- 22
prob_red_spheres <- function(z) {
  total_balls <- num_red_balls + num_blue_balls
  log_prob <- log(choose(total_draws, z)) + z * log(num_red_balls / total_balls) + (total_draws - z) * log(num_blue_balls / total_balls)
  return(exp(log_prob))
}
num_trials <- 1000
set.seed(0)
num_reds_in_simulation <- tibble(trial = 1:num_trials) %>% mutate(sample_balls = map(trial, ~ sample(1:10, total_draws, replace = TRUE))) %>% mutate(num_reds = map_dbl(sample_balls, ~ sum(.x <= 3))) %>% pull(num_reds)
prob_by_num_reds <- tibble(num_reds = seq(0, total_draws)) %>% mutate(TheoreticalProbability = prob_red_spheres(num_reds)) %>% mutate(EstimatedProbability = map_dbl(num_reds, ~ sum(num_reds_in_simulation == .x) / num_trials))
prob_by_num_reds
```
## (Q2)
```{r}
prob_by_num_reds %>% pivot_longer(cols = c("EstimatedProbability", "TheoreticalProbability"), names_to = "Type", values_to = "count") %>% ggplot(aes(num_reds, count)) + geom_line(aes(linetype = Type, color = Type)) + geom_point(aes(color = Type)) + scale_linetype_manual(values = c("solid", "dashed")) + theme_bw() + xlab("Number of reds") + ylab("Probabilities")
```